/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AbstractProductA;

import javax.swing.JButton;

/**
 *
 * @author MK
 */
public class Panel2 extends Panel {

    /**
     * Creates new form Panel2
     */
    public Panel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstruktor = new javax.swing.JLabel();
        btnKreiraj = new javax.swing.JButton();
        lblCena = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnPronadji = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        txtInstruktor = new javax.swing.JTextField();
        txtCena = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblBrojPolazinka = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        txtBrojPolaznika = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lblCena2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPoruka = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblInstruktor.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblInstruktor.setForeground(new java.awt.Color(13, 67, 114));
        lblInstruktor.setText("Instruktor:");

        btnKreiraj.setBackground(new java.awt.Color(124, 207, 247));
        btnKreiraj.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnKreiraj.setForeground(new java.awt.Color(251, 254, 254));
        btnKreiraj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnKreiraj.setText("Kreiraj");
        btnKreiraj.setBorder(null);
        btnKreiraj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKreiraj.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKreiraj.setIconTextGap(10);
        btnKreiraj.setPreferredSize(new java.awt.Dimension(75, 40));

        lblCena.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblCena.setForeground(new java.awt.Color(13, 67, 114));
        lblCena.setText("Cena:");

        btnIzmeni.setBackground(new java.awt.Color(124, 207, 247));
        btnIzmeni.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(251, 254, 254));
        btnIzmeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/change.png"))); // NOI18N
        btnIzmeni.setText("Izmeni");
        btnIzmeni.setBorder(null);
        btnIzmeni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIzmeni.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnIzmeni.setIconTextGap(10);
        btnIzmeni.setPreferredSize(new java.awt.Dimension(75, 40));

        btnObrisi.setBackground(new java.awt.Color(124, 207, 247));
        btnObrisi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnObrisi.setForeground(new java.awt.Color(251, 254, 254));
        btnObrisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove.png"))); // NOI18N
        btnObrisi.setText("Obriši");
        btnObrisi.setBorder(null);
        btnObrisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnObrisi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnObrisi.setIconTextGap(10);
        btnObrisi.setPreferredSize(new java.awt.Dimension(75, 40));

        btnPronadji.setBackground(new java.awt.Color(124, 207, 247));
        btnPronadji.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPronadji.setForeground(new java.awt.Color(251, 254, 254));
        btnPronadji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/find.png"))); // NOI18N
        btnPronadji.setText("Pronađi");
        btnPronadji.setBorder(null);
        btnPronadji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPronadji.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPronadji.setIconTextGap(10);
        btnPronadji.setPreferredSize(new java.awt.Dimension(75, 40));
        btnPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPronadjiActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(13, 67, 114));
        txtId.setBorder(null);

        txtNaziv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNaziv.setForeground(new java.awt.Color(13, 67, 114));
        txtNaziv.setBorder(null);

        txtInstruktor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtInstruktor.setForeground(new java.awt.Color(13, 67, 114));
        txtInstruktor.setBorder(null);

        txtCena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCena.setForeground(new java.awt.Color(13, 67, 114));
        txtCena.setBorder(null);

        lblId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(13, 67, 114));
        lblId.setText("ID:");

        lblBrojPolazinka.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblBrojPolazinka.setForeground(new java.awt.Color(13, 67, 114));
        lblBrojPolazinka.setText("Broj polaznika:");

        lblNaziv.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNaziv.setForeground(new java.awt.Color(13, 67, 114));
        lblNaziv.setText("Naziv plesnog kursa:");

        txtBrojPolaznika.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBrojPolaznika.setForeground(new java.awt.Color(13, 67, 114));
        txtBrojPolaznika.setBorder(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/balletShoes.jpg"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(13, 67, 114));

        jSeparator2.setForeground(new java.awt.Color(13, 67, 114));

        jSeparator3.setForeground(new java.awt.Color(13, 67, 114));

        jSeparator4.setForeground(new java.awt.Color(13, 67, 114));

        jSeparator5.setForeground(new java.awt.Color(13, 67, 114));

        lblCena2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCena2.setForeground(new java.awt.Color(13, 67, 114));
        lblCena2.setText("din./mesečno");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 67, 114)));
        jPanel1.setForeground(new java.awt.Color(13, 67, 114));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        txtPoruka.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtPoruka.setForeground(new java.awt.Color(0, 147, 122));
        txtPoruka.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPoruka.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNaziv)
                                .addComponent(lblInstruktor, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCena, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblBrojPolazinka, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(lblId)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator2)
                            .addComponent(txtNaziv)
                            .addComponent(txtInstruktor)
                            .addComponent(txtBrojPolaznika)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnPronadji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCena2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblId)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNaziv)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInstruktor)
                            .addComponent(txtInstruktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCena)
                            .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCena2))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBrojPolazinka)
                            .addComponent(txtBrojPolaznika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPronadjiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPronadjiActionPerformed

    @Override
    public javax.swing.JTextField getId1() {
        return txtId;
    }
    
    @Override
    public String getId() {
        return txtId.getText();
    }

    @Override
    public String getNaziv() {
        return txtNaziv.getText();
    }

    @Override
    public String getInstruktor() {
        return txtInstruktor.getText();
    }

    @Override
    public String getCena() {
        return txtCena.getText();
    }

    @Override
    public String getBrojPolaznika() {
        return txtBrojPolaznika.getText();
    }

    
    @Override
    public void setPoruka(String Poruka1) {
        txtPoruka.setText(Poruka1);
    }
    
    @Override
    public void setId(String id) {
        txtId.setText(id);
    }

    @Override
    public void setNaziv(String naziv) {
        txtNaziv.setText(naziv);
    }

    @Override
    public void setInstruktor(String instruktor) {
        txtInstruktor.setText(instruktor);
    }

    @Override
    public void setCena(String cena) {
        txtCena.setText(cena);
    }

    @Override
    public void setBrojPolaznika(String brojPolaznika) {
        txtBrojPolaznika.setText(brojPolaznika);
    }

    @Override
    public JButton getKreiraj() {
        return btnKreiraj;
    }

    @Override
    public JButton getPromeni() {
        return btnIzmeni;
                
    }

    @Override
    public JButton getObrisi() {
        return btnObrisi;
    }

    @Override
    public JButton getNadji() {
        return btnPronadji;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPronadji;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblBrojPolazinka;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblCena2;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblInstruktor;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JTextField txtBrojPolaznika;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtInstruktor;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPoruka;
    // End of variables declaration//GEN-END:variables
}
